<?php


class ProductElements
{
    static public function getFruitProducts()
    {
        return [
            [
                'unit'          => "gramo",
                'sku'           => "MNGCMN1875",
                'name'          => "Mango Común",
                'description'   => "Mango pa jugo",
                'regularPrice'  => 3.75,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MNGTMMY1750",
                'name'          => "Mango Tommy",
                'description'   => "Mango maduro pa comer",
                'regularPrice'  => 1750/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MZNRJA4375",
                'name'          => "Manzana Roja",
                'description'   => "Manzana Roja",
                'regularPrice'  => 4375/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MRCY1750",
                'name'          => "Manzana Roja",
                'description'   => "Manzana Roja",
                'regularPrice'  => 1750/500,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "FRSS3750",
                'name'          => "Fresa",
                'description'   => "Fresa en bandeja",
                'regularPrice'  => 3750,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "GYB1750",
                'name'          => "Guayaba",
                'description'   => "Guayaba",
                'regularPrice'  => 1750/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "GRNDLL3750",
                'name'          => "Granadilla",
                'description'   => "Granadilla",
                'regularPrice'  => 3750/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "BNN1500",
                'name'          => "Banano",
                'description'   => "Banano",
                'regularPrice'  => 1500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "GNBN2104",
                'name'          => "Guanabana",
                'description'   => "Guanabana",
                'regularPrice'  => 2104/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PPYA875",
                'name'          => "Papaya",
                'description'   => "Papaya",
                'regularPrice'  => 875/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "TMTRBL2000",
                'name'          => "Tomate Árbol",
                'description'   => "Tomate Árbol",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PNAOM1250",
                'name'          => "Piña Oro Miel",
                'description'   => "Piña Oro Miel",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "USBL1875",
                'name'          => "Uva Isabel",
                'description'   => "Uva Isabel",
                'regularPrice'  => 1875,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "LMNTHT875",
                'name'          => "Limón Tahití",
                'description'   => "Limón Tahití",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CRBA1250",
                'name'          => "Curuba",
                'description'   => "Curuba",
                'regularPrice'  => 1250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "AGCTE3125",
                'name'          => "Aguacate",
                'description'   => "Aguacate",
                'regularPrice'  => 3125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MLN1875",
                'name'          => "Melón",
                'description'   => "Melón",
                'regularPrice'  => 1875/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "LUL2125",
                'name'          => "Lulo",
                'description'   => "Lulo",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "NRJVLCIA875",
                'name'          => "Naranja Valencia",
                'description'   => "Naranja Valencia",
                'regularPrice'  => 875/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MNDRNAARYN1250",
                'name'          => "Mandarina Arayana",
                'description'   => "Mandarina Arayana",
                'regularPrice'  => 1250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PTHYA5000",
                'name'          => "Pithaya",
                'description'   => "Pithaya",
                'regularPrice'  => 5000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MRA2500",
                'name'          => "Mora",
                'description'   => "Mora",
                'regularPrice'  => 2500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "SNDA875",
                'name'          => "Sandia",
                'description'   => "Sandia",
                'regularPrice'  => 875/500,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "KWBJA7500",
                'name'          => "Kiwi",
                'description'   => "Kiwi",
                'regularPrice'  => 7500,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "PRANAL875",
                'name'          => "Pera Nacional",
                'description'   => "Pera Nacional",
                'regularPrice'  => 875/500,
            ],
        ];
    }

    public static function getPulpFruitProducts()
    {
        return [
            [
                'unit'          => "libra",
                'sku'           => "UVPLP2640",
                'name'          => "Pulpa Uva",
                'description'   => "Pulpa de uva",
                'regularPrice'  => 2640,
            ],
            [
                'unit'          => "libra",
                'sku'           => "MRCYPLP4200",
                'name'          => "Pulpa Maracuya",
                'description'   => "Pulpa de maracuya",
                'regularPrice'  => 4200,
            ],
            [
                'unit'          => "libra",
                'sku'           => "LULPLP3600",
                'name'          => "Pulpa Lulo",
                'description'   => "Pulpa de lulo",
                'regularPrice'  => 3600,
            ],
            [
                'unit'          => "libra",
                'sku'           => "MNGPLP3000",
                'name'          => "Pulpa Mango",
                'description'   => "Pulpa de mango",
                'regularPrice'  => 3000,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "GNBNAPLP3120",
                'name'          => "Pulpa Guanabana",
                'description'   => "Pulpa de guanabana",
                'regularPrice'  => 3120,
            ],
        ];
    }

    public static function getVegetableProducts()
    {
        return [
            [
                'unit'          => "unidad",
                'sku'           => "MZRC750",
                'name'          => "Mazorca Común",
                'description'   => "Mazorca común",
                'regularPrice'  => 750,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PPAMRLL1725",
                'name'          => "Papa Amarilla",
                'description'   => "Papa amarilla",
                'regularPrice'  => 1725/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PLTNVRD1125",
                'name'          => "Platano Verde",
                'description'   => "Platano Verde",
                'regularPrice'  => 1125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PPPRD1000",
                'name'          => "Papa Parda",
                'description'   => "Papa Parda",
                'regularPrice'  => 1000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CLRY1250",
                'name'          => "Apio",
                'description'   => "Apio",
                'regularPrice'  => 1250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "BRCL3125",
                'name'          => "Brocolo",
                'description'   => "Brocolo",
                'regularPrice'  => 3125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "SPNC1250",
                'name'          => "Espinaca",
                'description'   => "Espinaca",
                'regularPrice'  => 1250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CLBCN2000",
                'name'          => "Calabacin",
                'description'   => "Calabacin",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CBLLRG1875",
                'name'          => "Cebolla Larga",
                'description'   => "Cebolla Larga",
                'regularPrice'  => 1875/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PPNO1000",
                'name'          => "Pepino",
                'description'   => "Pepino",
                'regularPrice'  => 1000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CBLCBZN2000",
                'name'          => "Cebolla Cabezona",
                'description'   => "Cebolla Cabezona",
                'regularPrice'  => 2000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PMNTN1625",
                'name'          => "Pimentón",
                'description'   => "Pimentón",
                'regularPrice'  => 1625/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "CBLLMRD2375",
                'name'          => "Cebolla Cabezona Morada",
                'description'   => "Cebolla Cabezona Morada",
                'regularPrice'  => 2375/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "GRLC7500",
                'name'          => "Ajo",
                'description'   => "Ajo",
                'regularPrice'  => 7500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "FJLVRD6500",
                'name'          => "Frijol Verde",
                'description'   => "Frijol Verde",
                'regularPrice'  => 6500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "ARRCH1500",
                'name'          => "Arracacha",
                'description'   => "Arracacha",
                'regularPrice'  => 1500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "MSHRMRM6250",
                'name'          => "Champiñón",
                'description'   => "Champiñón",
                'regularPrice'  => 6250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "ARVJ5000",
                'name'          => "Arveja",
                'description'   => "Arveja",
                'regularPrice'  => 5000/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "HBCHL1500",
                'name'          => "Habichuela",
                'description'   => "Habichuela",
                'regularPrice'  => 1500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "LCHGBTV1125",
                'name'          => "Lechuga Batavia",
                'description'   => "Lechuga Batavia",
                'regularPrice'  => 1125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "COLFLWR3125",
                'name'          => "Colifor",
                'description'   => "Colifor",
                'regularPrice'  => 3125/500,
            ],
            [
                'unit'          => "paquete",
                'sku'           => "LLQC4000",
                'name'          => "Olluco",
                'description'   => "Olluco",
                'regularPrice'  => 4000,
            ],
            [
                'unit'          => "bandeja",
                'sku'           => "CRNSWT1875",
                'name'          => "Maiz Dulce",
                'description'   => "Maiz Dulce",
                'regularPrice'  => 1875,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "YCA975",
                'name'          => "Yuca",
                'description'   => "Yuca",
                'regularPrice'  => 975/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "GUNO1125",
                'name'          => "Guineo",
                'description'   => "Guineo",
                'regularPrice'  => 1125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PLTGYB1750",
                'name'          => "Platano Guayabo",
                'description'   => "Platano Guayabo",
                'regularPrice'  => 1750/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "JGBR6250",
                'name'          => "Jengibre",
                'description'   => "Jengibre",
                'regularPrice'  => 6250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "BRNJN2250",
                'name'          => "Berenjena",
                'description'   => "Berenjena",
                'regularPrice'  => 2250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "PLTNMDR1250",
                'name'          => "Platano Maduro",
                'description'   => "Platano Maduro",
                'regularPrice'  => 1250/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "RMLCH875",
                'name'          => "Remolacha",
                'description'   => "Remolacha",
                'regularPrice'  => 875/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "TMTCHNT1500",
                'name'          => "Tomate Chonto",
                'description'   => "Tomate Chonto",
                'regularPrice'  => 1500/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "RPLL1125",
                'name'          => "Repollo",
                'description'   => "Repollo",
                'regularPrice'  => 1125/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "ZNHR1625",
                'name'          => "Zanahoria",
                'description'   => "Zanahoria",
                'regularPrice'  => 1625/500,
            ],
            [
                'unit'          => "gramo",
                'sku'           => "RPLLMRD1375",
                'name'          => "Repollo Morado",
                'description'   => "Repollo Morado",
                'regularPrice'  => 1375/500,
            ],
        ];
    }
}
